version: '3'
services:
  app:
    build: .
    image: test/app:latest
    ports:
      - 8080:8080
      - 8000:8000
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DATABASE=postgres